"""
Category Group Mapping - Amazon Purchase Histories
Map ~390 category con sang 18 nhóm lớn (macro category) theo nghĩa nghiệp vụ.
"""

category_mapping = {
    # 1. Books & Media
    "ABIS_BOOK": "Books & Media", "ABIS_MUSIC": "Books & Media",
    "PHYSICAL_MOVIE": "Books & Media", "PHYSICAL_VIDEO_GAME_SOFTWARE": "Books & Media",
    "DOWNLOADABLE_VIDEO_GAME": "Books & Media", "ABIS_DVD": "Books & Media",
    "PHYSICAL_TV_SERIES": "Books & Media", "BLANK_BOOK": "Books & Media",
    "COLLECTIBLE_CARD": "Books & Media",

    # 2. Electronics & Accessories
    "ELECTRONIC_CABLE": "Electronics & Accessories", "CELLULAR_PHONE_CASE": "Electronics & Accessories",
    "HEADPHONES": "Electronics & Accessories", "BATTERY": "Electronics & Accessories",
    "SCREEN_PROTECTOR": "Electronics & Accessories", "CHARGING_ADAPTER": "Electronics & Accessories",
    "PORTABLE_ELECTRONIC_DEVICE_COVER": "Electronics & Accessories", "FLASH_MEMORY": "Electronics & Accessories",
    "INPUT_MOUSE": "Electronics & Accessories", "COMPUTER_DRIVE_OR_STORAGE": "Electronics & Accessories",
    "ELECTRONIC_ADAPTER": "Electronics & Accessories", "POWER_STRIP": "Electronics & Accessories",
    "DIGITAL_DEVICE_3": "Electronics & Accessories", "DIGITAL_DEVICE_4": "Electronics & Accessories",
    "SPEAKERS": "Electronics & Accessories", "KEYBOARDS": "Electronics & Accessories",
    "REMOTE_CONTROL": "Electronics & Accessories", "CONSUMER_ELECTRONICS": "Electronics & Accessories",
    "WIRELESS_ACCESSORY": "Electronics & Accessories", "VIDEO_GAME_CONTROLLER": "Electronics & Accessories",
    "MOUSE_PAD": "Electronics & Accessories", "POWER_CORD": "Electronics & Accessories",
    "POWER_BANK": "Electronics & Accessories", "FLAT_SCREEN_DISPLAY_MOUNT": "Electronics & Accessories",
    "NETWORK_INTERFACE_CONTROLLER_ADAPTER": "Electronics & Accessories", "ELECTRONIC_SWITCH": "Electronics & Accessories",
    "ELECTRONIC_COMPONENT_FAN": "Electronics & Accessories", "FLASH_DRIVE": "Electronics & Accessories",
    "MICROPHONE": "Electronics & Accessories", "VIDEO_GAME_ACCESSORIES": "Electronics & Accessories",
    "WEARABLE_COMPUTER": "Electronics & Accessories", "MONITOR": "Electronics & Accessories",
    "AMAZON_TABLET": "Electronics & Accessories", "NOTEBOOK_COMPUTER": "Electronics & Accessories",
    "INTERNAL_MEMORY": "Electronics & Accessories", "NETWORKING_ROUTER": "Electronics & Accessories",
    "PRINTER": "Electronics & Accessories", "BATTERY_CHARGER": "Electronics & Accessories",
    "INKJET_PRINTER_INK": "Electronics & Accessories", "CAMCORDER": "Electronics & Accessories",
    "MULTIPORT_HUB": "Electronics & Accessories", "SECURITY_CAMERA": "Electronics & Accessories",
    "CELLULAR_PHONE": "Electronics & Accessories", "STANDALONE_STREAMING_MEDIA_PLAYER": "Electronics & Accessories",
    "VDO_DEVICES": "Electronics & Accessories", "PORTABLE_ELECTRONIC_DEVICE_MOUNT": "Electronics & Accessories",
    "PORTABLE_ELECTRONIC_DEVICE_STAND": "Electronics & Accessories", "WATCH_BAND": "Electronics & Accessories",
    "INPUT_PEN": "Electronics & Accessories", "CELL_PHONE_GRIP": "Electronics & Accessories",

    # 3. Apparel & Fashion
    "SHIRT": "Apparel & Fashion", "PANTS": "Apparel & Fashion", "SHOES": "Apparel & Fashion",
    "DRESS": "Apparel & Fashion", "UNDERPANTS": "Apparel & Fashion", "BRA": "Apparel & Fashion",
    "SHORTS": "Apparel & Fashion", "HAT": "Apparel & Fashion", "SWIMWEAR": "Apparel & Fashion",
    "SOCKS": "Apparel & Fashion", "SWEATSHIRT": "Apparel & Fashion", "SWEATER": "Apparel & Fashion",
    "COAT": "Apparel & Fashion", "BOOT": "Apparel & Fashion", "SANDAL": "Apparel & Fashion",
    "TUNIC": "Apparel & Fashion", "LEOTARD": "Apparel & Fashion", "TIGHTS": "Apparel & Fashion",
    "APPAREL": "Apparel & Fashion", "APPAREL_BELT": "Apparel & Fashion", "PAJAMAS": "Apparel & Fashion",
    "SKIRT": "Apparel & Fashion", "COSTUME_OUTFIT": "Apparel & Fashion", "COORDINATED_OUTFIT": "Apparel & Fashion",
    "APPAREL_HEAD_NECK_COVERING": "Apparel & Fashion", "APPAREL_GLOVES": "Apparel & Fashion",
    "NIGHTGOWN_NIGHTSHIRT": "Apparel & Fashion", "HAIRBAND": "Apparel & Fashion",
    "SLIPPER": "Apparel & Fashion", "ROBE": "Apparel & Fashion", "WIG": "Apparel & Fashion",
    "SHOELACE": "Apparel & Fashion", "FABRIC": "Apparel & Fashion", "COSTUME_HEADWEAR": "Apparel & Fashion",

    # 4. Jewelry & Bags
    "NECKLACE": "Jewelry & Bags", "EARRING": "Jewelry & Bags", "RING": "Jewelry & Bags",
    "BRACELET": "Jewelry & Bags", "WATCH": "Jewelry & Bags", "PIERCING_JEWELRY": "Jewelry & Bags",
    "WALLET": "Jewelry & Bags", "HANDBAG": "Jewelry & Bags", "BACKPACK": "Jewelry & Bags",
    "SUNGLASSES": "Jewelry & Bags", "KEYCHAIN": "Jewelry & Bags", "JEWELRY_STORAGE": "Jewelry & Bags",
    "CHARM": "Jewelry & Bags", "CARD_DOCUMENT_SLEEVE": "Jewelry & Bags", "COSMETIC_CASE": "Jewelry & Bags",

    # 5. Beauty & Personal Care
    "SKIN_MOISTURIZER": "Beauty & Personal Care", "SKIN_CLEANING_AGENT": "Beauty & Personal Care",
    "BEAUTY": "Beauty & Personal Care", "HAIR_STYLING_AGENT": "Beauty & Personal Care",
    "SHAMPOO": "Beauty & Personal Care", "CONDITIONER": "Beauty & Personal Care",
    "BODY_DEODORANT": "Beauty & Personal Care", "SKIN_TREATMENT_MASK": "Beauty & Personal Care",
    "HAIR_COLORING_AGENT": "Beauty & Personal Care", "NAIL_POLISH": "Beauty & Personal Care",
    "LIP_BALM": "Beauty & Personal Care", "HAIR_BRUSH": "Beauty & Personal Care",
    "SUNSCREEN": "Beauty & Personal Care", "ESSENTIAL_OIL": "Beauty & Personal Care",
    "SKIN_EXFOLIANT": "Beauty & Personal Care", "EYELID_COLOR": "Beauty & Personal Care",
    "SKIN_FOUNDATION_CONCEALER": "Beauty & Personal Care", "MOUTHWASH": "Beauty & Personal Care",
    "MANUAL_SHAVING_RAZOR": "Beauty & Personal Care", "TOOTH_CLEANING_AGENT": "Beauty & Personal Care",
    "PERSONAL_FRAGRANCE": "Beauty & Personal Care", "HAIR_CLIP": "Beauty & Personal Care",
    "SKIN_SERUM": "Beauty & Personal Care", "BODY_LUBRICANT": "Beauty & Personal Care",
    "LIP_COLOR": "Beauty & Personal Care", "MASCARA": "Beauty & Personal Care",
    "COSMETIC_BRUSH": "Beauty & Personal Care", "HAIR_CLEANER_CONDITIONER": "Beauty & Personal Care",
    "ASTRINGENT_SUBSTANCE": "Beauty & Personal Care", "FALSE_NAIL": "Beauty & Personal Care",
    "EYEBROW_COLOR": "Beauty & Personal Care", "HAIR_REMOVAL_AGENT": "Beauty & Personal Care",
    "FALSE_EYELASH": "Beauty & Personal Care", "HAIR_IRON": "Beauty & Personal Care",
    "TOPICAL_HAIR_REGROWTH_TREATMENT": "Beauty & Personal Care", "HAIR_DRYER": "Beauty & Personal Care",
    "HAIR_TIE": "Beauty & Personal Care", "HAIR_TRIMMER": "Beauty & Personal Care",
    "HAIR_COMB": "Beauty & Personal Care", "ELECTRIC_SHAVER": "Beauty & Personal Care",
    "RAZOR_BLADE_CARTRIDGE": "Beauty & Personal Care", "TOOTHBRUSH": "Beauty & Personal Care",
    "TOOTHBRUSH_HEAD": "Beauty & Personal Care", "DENTAL_FLOSS": "Beauty & Personal Care",
    "TOOTH_WHITENER": "Beauty & Personal Care", "SKIN_CLEANING_WIPE": "Beauty & Personal Care",
    "SHOE_INSERT": "Beauty & Personal Care",

    # 6. Health & Wellness
    "NUTRITIONAL_SUPPLEMENT": "Health & Wellness", "MEDICATION": "Health & Wellness",
    "HEALTH_PERSONAL_CARE": "Health & Wellness", "VITAMIN": "Health & Wellness",
    "HERBAL_SUPPLEMENT": "Health & Wellness", "MINERAL_SUPPLEMENT": "Health & Wellness",
    "PROTEIN_SUPPLEMENT_POWDER": "Health & Wellness", "INCONTINENCE_PROTECTOR": "Health & Wellness",
    "SAFETY_MASK": "Health & Wellness", "ORTHOPEDIC_BRACE": "Health & Wellness",
    "WOUND_DRESSING": "Health & Wellness", "MEDICAL_TEST_STRIP": "Health & Wellness",
    "PERSONAL_PILL_DISPENSER": "Health & Wellness", "PROFESSIONAL_HEALTHCARE": "Health & Wellness",
    "SANITARY_NAPKIN": "Health & Wellness", "THERMOMETER": "Health & Wellness",
    "RESPIRATOR": "Health & Wellness", "PROTECTIVE_GLOVE": "Health & Wellness",
    "SAFETY_GLASSES": "Health & Wellness", "THERAPEUTIC_THERMAL_COMPRESS": "Health & Wellness",
    "EARPLUG": "Health & Wellness", "INSECT_REPELLENT": "Health & Wellness",
    "BODY_POSITIONER": "Health & Wellness", "WEIGH_SCALE": "Health & Wellness",
    "SLEEP_MASK": "Health & Wellness", "MASSAGER": "Health & Wellness",
    "EXERCISE_BAND": "Health & Wellness", "PROTEIN_DRINK": "Health & Wellness",
    "MEAL_REPLACEMENT_BEVERAGE": "Health & Wellness", "SEXUAL_STIMULATION_DEVICE": "Health & Wellness",

    # 7. Pet Supplies
    "PET_FOOD": "Pet Supplies", "PET_SUPPLIES": "Pet Supplies", "PET_TOY": "Pet Supplies",
    "ANIMAL_LITTER": "Pet Supplies", "PET_FEEDER": "Pet Supplies", "ANIMAL_COLLAR": "Pet Supplies",
    "PET_BED_MAT": "Pet Supplies", "PET_PEST_CONTROL": "Pet Supplies",
    "ANIMAL_NUTRITIONAL_SUPPLEMENT": "Pet Supplies", "PET_APPAREL": "Pet Supplies",
    "ANIMAL_WATER_DISPENSER": "Pet Supplies", "ANIMAL_HARNESS": "Pet Supplies",
    "LEASH": "Pet Supplies", "LITTER_BOX": "Pet Supplies",

    # 8. Grocery & Food
    "FOOD": "Grocery & Food", "GROCERY": "Grocery & Food", "VEGETABLE": "Grocery & Food",
    "FRUIT": "Grocery & Food", "COFFEE": "Grocery & Food", "DRINK_FLAVORED": "Grocery & Food",
    "SNACK_FOOD_BAR": "Grocery & Food", "TEA": "Grocery & Food", "SUGAR_CANDY": "Grocery & Food",
    "SNACK_CHIP_AND_CRISP": "Grocery & Food", "DAIRY_BASED_CHEESE": "Grocery & Food",
    "SAUCE": "Grocery & Food", "COOKIE": "Grocery & Food", "BREAKFAST_CEREAL": "Grocery & Food",
    "MEAT": "Grocery & Food", "NUT_AND_SEED": "Grocery & Food", "BREAD": "Grocery & Food",
    "PACKAGED_SOUP_AND_STEW": "Grocery & Food", "POULTRY": "Grocery & Food",
    "CHOCOLATE_CANDY": "Grocery & Food", "HERB": "Grocery & Food", "NOODLE": "Grocery & Food",
    "JUICE_AND_JUICE_DRINK": "Grocery & Food", "FRUIT_SNACK": "Grocery & Food",
    "CRACKER": "Grocery & Food", "CONDIMENT": "Grocery & Food", "DAIRY_BASED_DRINK": "Grocery & Food",
    "EDIBLE_OIL_VEGETABLE": "Grocery & Food", "FISH": "Grocery & Food", "SEASONING": "Grocery & Food",
    "DAIRY_BASED_YOGURT": "Grocery & Food", "SYRUP": "Grocery & Food", "CHEWING_GUM": "Grocery & Food",
    "NUT_BUTTER": "Grocery & Food", "MILK_SUBSTITUTE": "Grocery & Food",
    "DAIRY_BASED_ICE_CREAM": "Grocery & Food", "BAKING_MIX": "Grocery & Food", "CEREAL": "Grocery & Food",
    "FLOUR": "Grocery & Food", "CAKE": "Grocery & Food", "DAIRY_BASED_CREAM": "Grocery & Food",
    "PASTRY": "Grocery & Food", "PRETZEL": "Grocery & Food", "PUFFED_SNACK": "Grocery & Food",
    "EGG": "Grocery & Food", "SALAD_DRESSING": "Grocery & Food", "CULINARY_SALT": "Grocery & Food",
    "LEGUME": "Grocery & Food", "JERKY": "Grocery & Food", "SNACK_MIX": "Grocery & Food",
    "POPCORN": "Grocery & Food", "WATER": "Grocery & Food", "LEAVENING_AGENT": "Grocery & Food",
    "THICKENING_AGENT": "Grocery & Food", "SUGAR_SUBSTITUTE": "Grocery & Food",
    "FLAVORED_DRINK_CONCENTRATE": "Grocery & Food",

    # 9. Home & Furniture
    "HOME": "Home & Furniture", "KITCHEN": "Home & Furniture", "BLANKET": "Home & Furniture",
    "LAMP": "Home & Furniture", "CURTAIN": "Home & Furniture", "TOWEL": "Home & Furniture",
    "FOOD_STORAGE_CONTAINER": "Home & Furniture", "BOTTLE": "Home & Furniture", "CADDY": "Home & Furniture",
    "RUG": "Home & Furniture", "WALL_ART": "Home & Furniture", "BED_LINEN_SET": "Home & Furniture",
    "STORAGE_HOOK": "Home & Furniture", "SHELF": "Home & Furniture", "PICTURE_FRAME": "Home & Furniture",
    "PILLOW": "Home & Furniture", "FOOD_STORAGE_BAG": "Home & Furniture", "STORAGE_BAG": "Home & Furniture",
    "PLANTER": "Home & Furniture", "LIGHT_FIXTURE": "Home & Furniture", "MATTRESS_COVER": "Home & Furniture",
    "CHAIR": "Home & Furniture", "TABLE": "Home & Furniture", "DESK": "Home & Furniture",
    "BED_FRAME": "Home & Furniture", "DRINKING_CUP": "Home & Furniture", "THERMOS": "Home & Furniture",
    "TRASH_CAN": "Home & Furniture", "KITCHEN_KNIFE": "Home & Furniture", "SAUTE_FRY_PAN": "Home & Furniture",
    "BAKING_PAN": "Home & Furniture", "MEASURING_CUP": "Home & Furniture", "CUTTING_BOARD": "Home & Furniture",
    "MEAL_HOLDER": "Home & Furniture", "FOOD_SPATULA": "Home & Furniture", "COFFEE_MAKER": "Home & Furniture",
    "COFFEE_FILTER": "Home & Furniture", "VACUUM_CLEANER": "Home & Furniture", "STORAGE_BOX": "Home & Furniture",
    "STORAGE_RACK": "Home & Furniture", "FURNITURE_COVER": "Home & Furniture", "MATTRESS": "Home & Furniture",
    "CANDLE": "Home & Furniture", "CLOCK": "Home & Furniture", "HOME_MIRROR": "Home & Furniture",
    "HOME_LIGHTING_ACCESSORY": "Home & Furniture", "STRING_LIGHT": "Home & Furniture",
    "LIGHT_BULB": "Home & Furniture", "TABLECLOTH": "Home & Furniture", "PILLOWCASE": "Home & Furniture",
    "FITTED_SHEET": "Home & Furniture", "DECORATIVE_PILLOW_COVER": "Home & Furniture",
    "BASKET": "Home & Furniture", "HOME_BED_AND_BATH": "Home & Furniture", "DRYING_RACK": "Home & Furniture",
    "LAUNDRY_HAMPER": "Home & Furniture", "BEDDING_SET": "Home & Furniture",
    "ARTIFICIAL_PLANT": "Home & Furniture", "DECORATIVE_SIGNAGE": "Home & Furniture",
    "DECORATIVE_MAGNET": "Home & Furniture", "FLASHLIGHT": "Home & Furniture", "UMBRELLA": "Home & Furniture",
    "ITEM_CONTAINER": "Home & Furniture", "CONTAINER_LID": "Home & Furniture",
    "SPRAY_BOTTLE": "Home & Furniture", "AROMA_DIFFUSER": "Home & Furniture", "HUMIDIFIER": "Home & Furniture",
    "AIR_PURIFIER": "Home & Furniture", "MAJOR_HOME_APPLIANCES": "Home & Furniture",
    "HANGING_ORNAMENT": "Home & Furniture",

    # 10. Cleaning & Household Supplies
    "CLEANING_AGENT": "Cleaning & Household Supplies", "LAUNDRY_DETERGENT": "Cleaning & Household Supplies",
    "WASTE_BAG": "Cleaning & Household Supplies", "TOILET_PAPER": "Cleaning & Household Supplies",
    "DISHWASHER_DETERGENT": "Cleaning & Household Supplies", "UTILITY_SPONGE": "Cleaning & Household Supplies",
    "SURFACE_CLEANING_WIPE": "Cleaning & Household Supplies", "FABRIC_SOFTENER": "Cleaning & Household Supplies",
    "PAPER_TOWEL": "Cleaning & Household Supplies", "CLEANING_BRUSH": "Cleaning & Household Supplies",
    "AREA_DEODORIZER": "Cleaning & Household Supplies", "FACIAL_TISSUE": "Cleaning & Household Supplies",
    "LINT_REMOVER": "Cleaning & Household Supplies", "MACHINE_LUBRICANT": "Cleaning & Household Supplies",
    "BATHWATER_ADDITIVE": "Cleaning & Household Supplies", "PEST_CONTROL_DEVICE": "Cleaning & Household Supplies",
    "PESTICIDE": "Cleaning & Household Supplies", "FERTILIZER": "Cleaning & Household Supplies",

    # 11. Toys, Games & Hobbies
    "TOYS_AND_GAMES": "Toys, Games & Hobbies", "TOY_FIGURE": "Toys, Games & Hobbies",
    "TABLETOP_GAME": "Toys, Games & Hobbies", "TOY_BUILDING_BLOCK": "Toys, Games & Hobbies",
    "FIGURINE": "Toys, Games & Hobbies", "PUZZLES": "Toys, Games & Hobbies",
    "BOARD_GAME": "Toys, Games & Hobbies", "NON_RIDING_TOY_VEHICLE": "Toys, Games & Hobbies",
    "FIDGET_TOY": "Toys, Games & Hobbies", "TOY_FIGURE_PLAYSET": "Toys, Games & Hobbies",
    "BALLOON": "Toys, Games & Hobbies", "ART_CRAFT_KIT": "Toys, Games & Hobbies",
    "ART_SUPPLIES": "Toys, Games & Hobbies", "ART_MEDIA_PAPER": "Toys, Games & Hobbies",
    "CRAFT_BEAD": "Toys, Games & Hobbies", "YARN": "Toys, Games & Hobbies",
    "ART_AND_CRAFT_SUPPLY": "Toys, Games & Hobbies",

    # 12. Office & School Supplies
    "WRITING_INSTRUMENT": "Office & School Supplies", "MARKING_PEN": "Office & School Supplies",
    "OFFICE_PRODUCTS": "Office & School Supplies", "LABEL": "Office & School Supplies",
    "PLANNER": "Office & School Supplies", "PRINT_COPY_PAPER": "Office & School Supplies",
    "ENVELOPE": "Office & School Supplies", "CALENDAR": "Office & School Supplies",
    "WRITING_BOARD": "Office & School Supplies", "FILE_FOLDER": "Office & School Supplies",
    "STICKER_DECAL": "Office & School Supplies", "GREETING_CARD": "Office & School Supplies",
    "GIFT_WRAP": "Office & School Supplies", "BANNER": "Office & School Supplies",
    "ADHESIVE_TAPES": "Office & School Supplies",

    # 13. Sports & Outdoors
    "SPORTING_GOODS": "Sports & Outdoors", "OUTDOOR_LIVING": "Sports & Outdoors",
    "OUTDOOR_RECREATION_PRODUCT": "Sports & Outdoors", "RECREATION_BALL": "Sports & Outdoors",
    "SPORT_ACTIVITY_GLOVE": "Sports & Outdoors",

    # 14. Tools & Home Improvement
    "TOOLS": "Tools & Home Improvement", "HARDWARE_HANDLE": "Tools & Home Improvement",
    "HARDWARE_TUBING": "Tools & Home Improvement", "HARDWARE": "Tools & Home Improvement",
    "BONDING_ADHESIVES": "Tools & Home Improvement", "LOCK": "Tools & Home Improvement",
    "PAINT": "Tools & Home Improvement", "PAINT_BRUSH": "Tools & Home Improvement",
    "SCREWDRIVER": "Tools & Home Improvement", "KNIFE": "Tools & Home Improvement",
    "VALVE": "Tools & Home Improvement", "PLUMBING_FIXTURE": "Tools & Home Improvement",
    "BUILDING_MATERIAL": "Tools & Home Improvement", "THERMOPLASTIC_FILAMENT": "Tools & Home Improvement",
    "HVAC_AIR_FILTER": "Tools & Home Improvement", "ELECTRIC_FAN": "Tools & Home Improvement",
    "HANGING_ROD": "Tools & Home Improvement", "HOSE_PIPE_FITTING": "Tools & Home Improvement",
    "WIPER_BLADE": "Tools & Home Improvement", "AUTO_ACCESSORY": "Tools & Home Improvement",
    "AUTO_PART": "Tools & Home Improvement", "LAB_SUPPLY": "Tools & Home Improvement",
    "WATER_PURIFICATION_UNIT": "Tools & Home Improvement", "POTABLE_WATER_FILTER": "Tools & Home Improvement",

    # 15. Baby & Maternity
    "BABY_PRODUCT": "Baby & Maternity",

    # 16. Gift Cards
    "GIFT_CARD": "Gift Cards", "ABIS_GIFT_CARD": "Gift Cards", "ELECTRONIC_GIFT_CARD": "Gift Cards",

    # 17. Bags & Carriers (misc small)
    "CARRIER_BAG_CASE": "Jewelry & Bags",
}

# Category nào không nằm trong dict này -> sẽ tự rơi vào "OTHER" khi áp dụng .fillna("OTHER")